#!/usr/bin/env python3
"""
supabase/generate_seed_sql.py

Reads the site's existing data/questions-intro.json and
data/questions-advanced.json and writes supabase/seed_questions.sql — one
INSERT per question, ready to paste into the Supabase SQL Editor after
schema.sql.

WHY GENERATE RATHER THAN HAND-WRITE THIS FILE:
The 30 questions already exist, reviewed and correct, in the JSON files.
Retyping them into SQL by hand is exactly the kind of step where a copy-paste
slip silently changes a `correct` index or drops an explanation — and this
site has already been burned once by a hand-maintained value quietly going
wrong (see the Clause 7 story in DESIGN.md). Generating the SQL from the same
JSON the site already trusts means there is only one place the content can be
wrong, not two.

Run it again any time data/questions-intro.json or data/questions-advanced.json
changes, then re-paste the regenerated seed_questions.sql into Supabase.

Usage (from the repo root):
    python supabase/generate_seed_sql.py
"""

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "data"
OUTPUT_PATH = Path(__file__).resolve().parent / "seed_questions.sql"

# Must match the course_version id seeded by schema.sql.
COURSE_VERSION_ID = "22222222-2222-2222-2222-222222222222"

SOURCE_FILES = {
    "intro": DATA_DIR / "questions-intro.json",
    "advanced": DATA_DIR / "questions-advanced.json",
}


def sql_string(value):
    """Wrap a Python string as a single-quoted SQL literal, doubling any
    internal single quotes — the standard SQL escaping rule. Returns the
    literal `NULL` (unquoted) for None."""
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def options_jsonb(options):
    """Turn a Python list of option strings into a `'[...]'::jsonb` literal.
    json.dumps produces double-quoted JSON, so the only characters that still
    need SQL-escaping afterwards are single quotes (apostrophes inside an
    option's own text, e.g. "manufacturer's")."""
    json_text = json.dumps(options)
    return sql_string(json_text) + "::jsonb"


def build_inserts():
    lines = []
    lines.append("-- ============================================================")
    lines.append("-- supabase/seed_questions.sql  (GENERATED — do not hand-edit)")
    lines.append("--")
    lines.append("-- Generated by supabase/generate_seed_sql.py from data/questions-intro.json")
    lines.append("-- and data/questions-advanced.json. Run supabase/schema.sql FIRST — this file")
    lines.append("-- references the course_version row that schema.sql seeds.")
    lines.append("--")
    lines.append("-- Safe to re-run: each row's id is derived deterministically from its level")
    lines.append("-- and position, so re-running this file updates existing rows in place")
    lines.append("-- instead of duplicating them (ON CONFLICT ... DO UPDATE below).")
    lines.append("-- ============================================================")
    lines.append("")

    total = 0
    for level, path in SOURCE_FILES.items():
        if not path.exists():
            raise SystemExit(f"Expected question file not found: {path}")

        questions = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(questions, list) or not questions:
            raise SystemExit(f"{path} did not contain a non-empty list of questions.")

        lines.append(f"-- ---------- {level} ({len(questions)} questions) ----------")

        for i, q in enumerate(questions):
            # Same validation quiz.js already performs at its own data
            # boundary (see loadQuestions() in quiz.js) — checked again here
            # so a malformed source file fails loudly at generation time
            # instead of silently producing bad seed SQL.
            options = q.get("options")
            correct = q.get("correct")
            valid_index = isinstance(correct, int) and isinstance(options, list) and 0 <= correct < len(options)
            if not q.get("q") or not isinstance(options, list) or not valid_index:
                raise SystemExit(f"Question {i + 1} in {path.name} is incomplete or malformed.")

            # A deterministic UUID-shaped id per (level, position) — NOT
            # gen_random_uuid() — is what makes re-running this file an
            # update rather than a duplicate insert. The first segment
            # encodes the level so intro and advanced ids can never collide.
            level_tag = "1" if level == "intro" else "2"
            row_id = f"33333333-3333-3333-3333-{level_tag}{i:011d}"

            lines.append(
                "insert into public.quiz_questions "
                "(id, course_version_id, level, question, options, correct_index, explanation, sort_order)"
            )
            lines.append(
                "values ("
                f"{sql_string(row_id)}, "
                f"{sql_string(COURSE_VERSION_ID)}, "
                f"{sql_string(level)}, "
                f"{sql_string(q['q'])}, "
                f"{options_jsonb(options)}, "
                f"{correct}, "
                f"{sql_string(q.get('explanation', ''))}, "
                f"{i})"
            )
            lines.append(
                "on conflict (id) do update set "
                "question = excluded.question, "
                "options = excluded.options, "
                "correct_index = excluded.correct_index, "
                "explanation = excluded.explanation, "
                "sort_order = excluded.sort_order;"
            )
            lines.append("")
            total += 1

    return lines, total


def main():
    lines, total = build_inserts()
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH} ({total} questions).")


if __name__ == "__main__":
    main()
